# configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: insta-pay-config-test
  namespace: testing
data:
  MONGODB_URI: "mongodb://test-mongo:27017/"
  MONGODB_DB: "insta_pay"
  USER_SERVICE_URL: "http://test-user-service:5000"
  TRANSACTION_SERVICE_URL: "http://test-transaction-service:5000"
  REACT_APP_ENV: "staging"
  REACT_APP_USER_SERVICE_URL: "http://test-user-service:5000"
  REACT_APP_TRANSACTION_SERVICE_URL: "http://test-transaction-service:5000"
  REACT_APP_REPORTING_SERVICE_URL: "http://test-reporting-service:5000"
  REACT_APP_API_TIMEOUT: "10000"
  REACT_APP_ENABLE_ANALYTICS: "false"
  REACT_APP_ENABLE_LOGGING: "true"
  REACT_APP_TITLE: "InstaPay"
  REACT_APP_DESCRIPTION: "Instant Money Transfer Platform"
  FLASK_APP: "app.py"
  FLASK_ENV: "testing"
  FLASK_DEBUG: "0"
  FLASK_HOST: "0.0.0.0"
  FLASK_PORT: "5000"
  SECRET_KEY: "192b9bdd22ab9ed4d12e236c78afcb9a393ec15f71bbf5dc987d54727823bcbf"