apiVersion: apps/v1
kind: Deployment
metadata:
  name: insta-front
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: insta-front
        image: mohamedsamir170/insta-front:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: insta-pay-config
            
        ports:
        - containerPort: 80

        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
